Release/2.0.0
Cray-HPE/console-data pull request #43
Opened 2023-03-27 18:55 UTC by jesseviola-hpe

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

This introduces a dependency that is backwards incompatible with console-operator <1.7.0

 - CASMCMS-8252: Update Chart with correct image and chart version strings during builds. Enabled building of unstable artifacts
 - CASMCMS-8156: Fix bug in handling Hill nodes. Spelling corrections.
 - CASMINST-5145: Update the base service chart to pull in necessary changes for upgraded istio

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

Backwards incompatible

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves CASMCMS-8252
* Resolves CASMCMS-8156
* Resolves CASMINST-5145
* Documentation changes required in [issue id](issue link)
* Merge after https://github.com/Cray-HPE/console-operator/pull/50

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `mug`

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2023-03-29 19:46 UTC, dlaine-hpe requested changes

2023-03-29 19:46 UTC, dlaine-hpe commented on console_data_svc/main.go
Copywrite.

2023-03-29 19:46 UTC, dlaine-hpe commented on integration_test/consolepod.go
Copywrite

2023-03-29 19:46 UTC, dlaine-hpe commented on integration_test/helpers.go
Copywrite

2023-03-29 19:46 UTC, dlaine-hpe commented on integration_test/inventory.go
Copywrite

2023-03-29 19:46 UTC, dlaine-hpe commented on console_data_svc/datastore.go
> +	if numNodeReplicas <= 0 {
I don't think we want to do this. This is a live call to console-operator. If the operator is down, we may as well let the console-data service still supply nodes to the console-node pods asking for more nodes.

There should be a post-check later so that if a pod is monitoring the node it is running on it will have the ability to re-assign later.

2023-03-29 19:46 UTC, dlaine-hpe commented on console_data_svc/datastore.go
There should be something in dbConsolePodHeartbeat that checks for if the pod is monitoring the node it is running on. That should be where it catches if the pod shifts workers or has somehow slipped through the cracks.

2023-04-06 19:55 UTC, rbak-hpe approved these changes

2023-04-07 14:23 UTC, dlaine-hpe requested changes
Just the one thing that needs a little tweak, the rest looks good.

2023-04-07 14:23 UTC, dlaine-hpe commented on console_data_svc/datastore.go
> +var selfMonitorCounter int = 0
Not sure I am sold on this one.
We are going to have systems out there with 10,000+ compute nodes and 50+ ncn workers.
Better to keep a list of 'console node pods that have nodes assigned to them' - if that is >1, then re-assign, if only one don't.

2023-04-07 20:41 UTC, dlaine-hpe approved these changes

2023-04-07 20:41 UTC, dlaine-hpe commented on console_data_svc/datastore.go
> +	if time.Duration(currentTimestamp-consolePodCache.timestamp) > 10*time.Minute {
Don't need to change, but usually 'magic numbers' (ie 10 minutes) should be:
1) easy to find (like const at top of file)
2) easy to change (env var set in helm chart user can access and modify)
3) well documented as to WHY you set it like you did - why 10 min? why not 1, or 30?

2023-04-07 22:59 UTC, merged